### ISSUE TITLE
NPM Package - Publish both minified and non-minified files

### ISSUE THREAD

**Issue by raybooysen** [esp/esp-js#149]
Since ESP is used as a library, end-users of the library will have better compression if we compress against non-minified files.  Uglify and the like are better able to minify with non-

Ideally, the NPM package would include a minified and non-minified output file including source maps for both.

http://stackoverflow.com/questions/25956937/how-to-build-minified-and-uncompressed-bundle-with-webpack

**Comment by KeithWoods** [comment]
fixed
