### ISSUE TITLE
Remove Dist folder

### ISSUE THREAD

**Issue by raybooysen** [esp/esp-js#33]
As esp-js is hosted on npm, we can do away with the dist folders.  It makes for very noise commits when we commit new versions.

**Comment by raybooysen** [comment]
So back on this issue, @KeithWoods you're keen to keep it for other consumers who won't use NPM. Is this a requirement?

**Comment by KeithWoods** [comment]
Not I think we should remove them. The current issues is just about transpiling dependencies: https://github.com/esp/esp-js/pull/34#discussion-diff-41102360L15

**Comment by raybooysen** [comment]
I'm confused, let me come over to your desk. :)

**Comment by KeithWoods** [comment]
ok :)
